let productosIniciales = [
    {id: 1, nombre: "barra de acero tipo Ø6", tipo: "aceros", desc: "bara de acero acindar", precio: 800, talle: "aceros", img: 'img/barrasDeAcero.webp', cantidad:1},
    {id: 2, nombre: "barra de acero tipo Ø8", tipo: "aceros", desc: "bara de acero acindar", precio: 850, talle: "aceros", img: 'img/barrasDeAcero.webp', cantidad:1},
    {id: 3, nombre: "barra de acero tipo Ø10", tipo: "aceros", desc: "bara de acero acindar", precio: 900, talle: "aceros", img: 'img/barrasDeAcero.webp', cantidad:1},
    {id: 4, nombre: "barra de acero tipo Ø12", tipo: "aceros", desc: "bara de acero acindar", precio: 950, talle: "aceros", img: 'img/barrasDeAcero.webp', cantidad:1},
    {id: 5, nombre: "barra de acero tipo Ø16", tipo: "aceros", desc: "bara de acero acindar", precio: 950, talle: "aceros", img: 'img/barrasDeAcero.webp', cantidad:1},
    {id: 6, nombre: "ladrillo comun", tipo: "mamposteria", desc: "ladrillo hueco", precio: 800, talle: "mamposteria", img: 'img/ladrilloComun.webp', cantidad:1},
    {id: 7, nombre: "ladrillo hueco 8", tipo: "mamposteria", desc: "ladrillo hueco", precio: 800, talle: "mamposteria", img: 'img/ladrilloHueco8.webp', cantidad:1},
    {id: 8, nombre: "ladrillo hueco 12", tipo: "mamposteria", desc: "ladrillo hueco", precio: 800, talle: "mamposteria", img: 'img/ladrilloHueco12.webp', cantidad:1},
    {id: 9, nombre: "ladrillo hueco 18", tipo: "mamposteria", desc: "ladrillo hueco", precio: 800, talle: "mamposteria", img: 'img/ladrilloHueco18.webp', cantidad:1},
    {id: 10, nombre: "ladrillo Retak 12", tipo: "mamposteria", desc: "ladrillo HCAC", precio: 800, talle: "mamposteria", img: 'img/ladrilloMacizo.webp', cantidad:1},
    {id: 11, nombre: "ladrillo Retak tipo 'U'", tipo: "mamposteria", desc: "ladrillo HCAC", precio: 800, talle: "mamposteria", img: 'img/ladrilloRetakU.webp', cantidad:1},
    {id: 12, nombre: "ladrillo Retak tipo 'O'", tipo: "mamposteria", desc: "ladrillo HCAC", precio: 800, talle: "mamposteria", img: 'img/ladrilloRetakO.webp', cantidad:1},
    {id: 13, nombre: "bolsa de 50kg", tipo: "aditivos", desc: "bolsa de cemento", precio: 800, talle: "aditivos", img: 'img/bolsaDeCemento.webp', cantidad:1},
    {id: 14, nombre: "bolsa de 20kg", tipo: "aditivos", desc: "bolsa de cal", precio: 650, talle: "aditivos", img: 'img/bolsaDeCal.webp', cantidad:1},
    {id: 15, nombre: "arena x m³", tipo: "aditivos", desc: "bolson de arena", precio: 1200, talle: "aditivos", img: 'img/bolsonDeArena.webp', cantidad:1},
    {id: 16, nombre: "cerecita de 20L", tipo: "aditivos", desc: "balde de cerecita", precio: 450, talle: "aditivos", img: 'img/cerecita.webp', cantidad:1},
    {id: 17, nombre: "carretilla", tipo: "herramientas", desc: "carretilla de transporte", precio: 800, talle: "herramientas", img: 'img/carretilla.webp', cantidad:1},
    {id: 18, nombre: "cuchara de albañil + balde", tipo: "herramientas", desc: "carretilla de transporte", precio: 800, talle: "herramientas", img: 'img/baldeCuchara.webp', cantidad:1},
    {id: 19, nombre: "pala punta ancha", tipo: "herramientas", desc: "carretilla de transporte", precio: 800, talle: "herramientas", img: 'img/palaAnchaPalaPunta.webp', cantidad:1},
    {id: 20, nombre: "llama metalica dientes", tipo: "herramientas", desc: "carretilla de transporte", precio: 800, talle: "herramientas", img: 'img/llanaMetalica.webp', cantidad:1},
    ]
